services:
  - type: web
    name: gym-reservation-system
    runtime: python3
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python gym_reservation_cloud.py
    envVars:
      - key: CONDOMISOFT_USERNAME
        sync: false
      - key: CONDOMISOFT_PASSWORD
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: TZ
        value: America/Mexico_City
    healthCheckPath: /health
    disk:
      name: gym-reservation-disk
      mountPath: /app/logs
      sizeGB: 1 