name: Gym Reservation Automation

on:
  schedule:
    # Run Monday, Wednesday, Friday at 00:01 AM Mexico City time (06:01 UTC)
    - cron: '1 6 * * 1,3,5'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  reserve-gym:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Chrome and dependencies
      run: |
        # Install required system packages
        sudo apt-get update -qq
        sudo apt-get install -y xvfb --no-install-recommends
        
        # Install Chrome using snap (faster than manual installation)
        sudo snap install chromium
        
        # Or alternatively, use the pre-installed Chrome if available
        if ! command -v google-chrome &> /dev/null && ! command -v chromium &> /dev/null; then
          # Fallback to manual installation if snap fails
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -qq
          sudo apt-get install -y google-chrome-stable --no-install-recommends
        fi
        
        # Install ChromeDriver
        LATEST_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip"
        sudo unzip -q /tmp/chromedriver.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        rm /tmp/chromedriver.zip
        
        # Verify installation
        chromedriver --version
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip --quiet
        pip install -r requirements.txt --quiet
    
    - name: Set up virtual display
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
    - name: Run gym reservation
      timeout-minutes: 10
      env:
        CONDOMISOFT_USERNAME: ${{ secrets.CONDOMISOFT_USERNAME }}
        CONDOMISOFT_PASSWORD: ${{ secrets.CONDOMISOFT_PASSWORD }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        TZ: America/Mexico_City
        DISPLAY: :99
      run: |
        python gym_reservation_cloud.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: gym-reservation-logs
        path: logs/
        retention-days: 30 